print("suma", 7+8)
print("resta",7-8)
print("multiplicacion",7*8)
print("division",7/8)
print("residuo",7%8)
print("denominador",7//8)
print("potencia",7**8)
print("valor abosluto",abs(-78))
print("max",max(7,8))
print("min",min(7,8))
print("redondeo",round(7.8))

from math import *
print("minimo entero",floor(1.7))
print("maximo entero",ceil(4.1))
print("raiz cuadrada",sqrt(6084))